import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

console.log("Starting migration script...");

const entriesPath = path.join(__dirname, '../data/entries.json');
const peoplePath = path.join(__dirname, '../data/people.json');
const outPath = path.join(__dirname, '../migrations/0002_import_data.sql');

try {
    const entriesRaw = fs.readFileSync(entriesPath, 'utf8');
    const entries = JSON.parse(entriesRaw);

    let people = [];
    if (fs.existsSync(peoplePath)) {
        const peopleRaw = fs.readFileSync(peoplePath, 'utf8');
        people = JSON.parse(peopleRaw);
    }

    let sql = '-- Migration generated by script\n';

    // Entries
    sql += '-- Entries\n';
    if (Array.isArray(entries)) {
        for (const entry of entries) {
            const id = entry.id;
            const kv = (entry.kvNummern && entry.kvNummern[0]) || entry.kv || '';
            const projectNumber = entry.projectNumber || '';
            const data = JSON.stringify(entry).replace(/'/g, "''"); // Escape single quotes
            const updatedAt = entry.modified || entry.ts || Date.now();

            sql += `INSERT OR IGNORE INTO entries (id, kv, projectNumber, data, updatedAt) VALUES ('${id}', '${kv}', '${projectNumber}', '${data}', ${updatedAt});\n`;
        }
    }

    // People
    sql += '-- People\n';
    if (Array.isArray(people)) {
        for (const person of people) {
            const id = person.id;
            const name = (person.name || '').replace(/'/g, "''");
            const email = (person.email || '').replace(/'/g, "''");
            const data = JSON.stringify(person).replace(/'/g, "''");
            const updatedAt = person.updatedAt || person.createdAt || Date.now();

            sql += `INSERT OR IGNORE INTO people (id, name, email, data, updatedAt) VALUES ('${id}', '${name}', '${email}', '${data}', ${updatedAt});\n`;
        }
    }

    fs.writeFileSync(outPath, sql);
    console.log(`Generated migration at ${outPath}`);

} catch (err) {
    console.error("Error generating migration:", err);
    process.exit(1);
}
